apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-games
resources:
  - api-genre-deploy.yaml
  - api-genre-svc.yaml
  - api-region-deploy.yaml
  - api-region-svc.yaml
  - game-store-db.yaml
  - game-store-db-svc.yaml
  - ingress-genre-region.yaml
  - namespace.yaml
configMapGenerator:
  - name: mysql-dump-config
    files:
    - videogames-db.sql
secretGenerator:
  - name: mysql-cred
    literals:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=video_games
    - MYSQL_HOST=game-store-db
    - MYSQL_USER=root


